baseURL = "http://da.qcri.org/rheem/"
#baseURL = "http://localhost/"
languageCode = "en-us"
title = "Rheem X-Platform"
theme = "airspace-hugo"
googleAnalytics = "UA-124750019-1"

[menu]

  [[menu.header]]
    weight = 2
    name = "About"
    url = "/about"
  [[menu.header]]
    weight = 3
    name = "Documentation"
    url = "/documentation"
  [[menu.header]]
    weight = 4
    name = "Publications"
    url = "/publication"
  [[menu.header]]
    weight = 5
    name = "People"
    url = "/people"
  [[menu.header]]
    weight = 6
    name = "Download"
    url = "/download"
  [[menu.header]]
    weight = 7
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About QCRI"
    url = "https://www.qcri.org/"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "/contact"
  [[menu.footer]]
    weight = 3
    name = "Fork me"
    url = "https://github.com/rheem-ecosystem"
  [[menu.footer]]
    weight = 4
    name = "License"
    url = "https://github.com/rheem-ecosystem/rheem/blob/master/LICENSE.TXT"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260
  correo = "jquianeruiz@hbku.edu.qa"
  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "The <strong>Cross-Platform</strong><br/>Data Processing<br/>System"
    class = "title-big"
    subtitle = ""

  [params.wrapper]
    enable = true
    italic = ""
    strong = "RHEEM"
    paragraph = "is a system designed to fully support cross-platform data processing. That is, it enables users to run data analytics over multiple data processing platforms. For this, it provides an abstraction on top of existing platforms in order to run data analytic tasks on top of any set of platforms. As a result, users can focus on the logics of their applications rather on the intricacies of the underlying platforms."
    img = "slider-bg.jpg"

  [params.call]
    enable = true
    title = "Turning a Zoo into a Circus"
    paragraph =  "<a class=\"nothing\" href=\"/about\">Read more</a> on how <b>RHEEM</b> tame the Zoo of existing data processing platforms to work together."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"




  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "HBKU Research Complex - PO Box 5825 - Doha, Qatar"
      email = "qcriinfo@qf.org.qa"
      phone = "+974 4454 0629"
      fax = "+974 4454 0630"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
